CREATE TABLE ROLES
(
    ROLE_ID BIGINT AUTO_INCREMENT NOT NULL,
    NAME    VARCHAR(255)          NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (ROLE_ID)
);

CREATE TABLE TWEETS
(
    ID         BINARY(16)   NOT NULL,
    CREATED_AT TIMESTAMP    NULL,
    USER_ID    BINARY(16)   NULL,
    CONTENT    VARCHAR(255) NULL,
    CONSTRAINT PK_TWEETS PRIMARY KEY (ID)
);

CREATE TABLE USERS
(
    ID         BINARY(16)   NOT NULL,
    CREATED_AT TIMESTAMP    NULL,
    USERNAME   VARCHAR(255) NULL,
    PASSWORD   VARCHAR(255) NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

CREATE TABLE USERS_ROLES
(
    ROLE_ID BIGINT     NOT NULL,
    USER_ID BINARY(16) NOT NULL,
    CONSTRAINT PK_USERS_ROLES PRIMARY KEY (ROLE_ID, USER_ID)
);

ALTER TABLE TWEETS
    ADD CONSTRAINT FK_TWEETS_ON_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

ALTER TABLE USERS
    ADD CONSTRAINT UC_USERS_USERNAME UNIQUE (USERNAME);

ALTER TABLE USERS_ROLES
    ADD CONSTRAINT FK_USEROL_ON_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID);

ALTER TABLE USERS_ROLES
    ADD CONSTRAINT FK_USEROL_ON_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID);